// Piloto V2 — UM template isolado. Cópia INDEPENDENTE do hipertrofia atual,
// reescrita em composição soberana (refeição = lista de itens reais).
// NÃO importa de src/lib/template-data.ts. NÃO é referenciado em produção.

import type { PlannerTemplateV2 } from "./template.v2.types";

export const espHipertrofiaV2Piloto: PlannerTemplateV2 = {
  id: "esp-hipertrofia-v2-piloto",
  name: "Hipertrofia — Piloto V2 (não publicar)",
  category: "Esportivo",
  description:
    "PILOTO V2. Demonstra item soberano: cada alimento com medidas, substituições e observações próprias.",
  tags: ["PILOTO_V2", "Hipertrofia"],
  kcal: 3000,
  v2: true,
  meals: [
    {
      id: "v2-m1",
      time: "07:00",
      label: "Café da manhã",
      notes: "Consumir até 30 min após o preparo.",
      items: [
        {
          id: "v2-m1-i1",
          foodKey: "pao_frances",
          name: "Pão francês",
          qty: 50,
          unit: "g",
          kcal: 150,
          proteinG: 5,
          carbG: 29,
          fatG: 1,
          scaleGroup: "carb",
          measures: [
            { label: "1 unidade", gramsEquivalent: 50, fromCatalog: true },
            { label: "1 fatia grande", gramsEquivalent: 40, fromCatalog: false },
          ],
          substitutions: [
            {
              foodKey: "tapioca",
              name: "Tapioca",
              qty: 40,
              unit: "g",
              kcal: 145,
              proteinG: 0,
              carbG: 36,
              fatG: 0,
              scaleGroup: "carb",
            },
            {
              foodKey: "cuscuz",
              name: "Cuscuz de milho",
              qty: 60,
              unit: "g",
              kcal: 150,
              proteinG: 3,
              carbG: 32,
              fatG: 1,
              scaleGroup: "carb",
            },
          ],
        },
        {
          id: "v2-m1-i2",
          foodKey: "ovo",
          name: "Ovo inteiro",
          qty: 2,
          unit: "unid",
          kcal: 140,
          proteinG: 12,
          carbG: 1,
          fatG: 10,
          scaleGroup: "protein",
          notes: "Preferir mexido ou cozido — evitar frituras.",
          measures: [
            { label: "2 ovos médios", gramsEquivalent: 100, fromCatalog: true },
          ],
          substitutions: [
            {
              foodKey: "queijo_minas",
              name: "Queijo minas",
              qty: 60,
              unit: "g",
              kcal: 145,
              proteinG: 11,
              carbG: 2,
              fatG: 10,
              scaleGroup: "protein",
            },
            {
              foodKey: "whey",
              name: "Whey protein",
              qty: 1,
              unit: "scoop",
              kcal: 120,
              proteinG: 24,
              carbG: 3,
              fatG: 1,
              scaleGroup: "protein",
              note: "Diluir em 200 ml de água.",
            },
          ],
        },
      ],
    },
    {
      id: "v2-m2",
      time: "13:00",
      label: "Almoço",
      items: [
        {
          id: "v2-m2-i1",
          foodKey: "frango_grelhado",
          name: "Frango grelhado",
          qty: 180,
          unit: "g",
          kcal: 300,
          proteinG: 55,
          carbG: 0,
          fatG: 7,
          scaleGroup: "protein",
          measures: [
            { label: "1 filé médio", gramsEquivalent: 130, fromCatalog: true },
            { label: "2 filés pequenos", gramsEquivalent: 180, fromCatalog: true },
            { label: "1 posta média", gramsEquivalent: 150, fromCatalog: false },
          ],
          substitutions: [
            {
              foodKey: "patinho",
              name: "Patinho",
              qty: 150,
              unit: "g",
              kcal: 290,
              proteinG: 52,
              carbG: 0,
              fatG: 9,
              scaleGroup: "protein",
            },
            {
              foodKey: "tilapia",
              name: "Filé de tilápia",
              qty: 200,
              unit: "g",
              kcal: 290,
              proteinG: 50,
              carbG: 0,
              fatG: 8,
              scaleGroup: "protein",
            },
          ],
        },
        {
          id: "v2-m2-i2",
          foodKey: "arroz_branco",
          name: "Arroz branco cozido",
          qty: 120,
          unit: "g",
          kcal: 155,
          proteinG: 3,
          carbG: 34,
          fatG: 0,
          scaleGroup: "carb",
        },
        {
          id: "v2-m2-i3",
          foodKey: "feijao_carioca",
          name: "Feijão carioca cozido",
          qty: 80,
          unit: "g",
          kcal: 60,
          proteinG: 5,
          carbG: 10,
          fatG: 0,
          scaleGroup: "carb",
        },
        {
          id: "v2-m2-i4",
          foodKey: "salada_verde",
          name: "Salada verde",
          qty: 100,
          unit: "g",
          kcal: 20,
          proteinG: 1,
          carbG: 3,
          fatG: 0,
          scaleGroup: "mixed",
          notes: "Temperar com azeite e limão.",
        },
      ],
    },
  ],
};
