/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LogoTestRouteImport } from './routes/logo-test'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupPatientRouteImport } from './routes/signup/patient'
import { Route as SignupNutritionistRouteImport } from './routes/signup/nutritionist'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthenticatedTemplatesV2EditorRouteImport } from './routes/_authenticated/templates-v2-editor'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProtocolosRouteImport } from './routes/_authenticated/protocolos'
import { Route as AuthenticatedMyPlanV2PreviewRouteImport } from './routes/_authenticated/my-plan-v2-preview'
import { Route as AuthenticatedMyPlanRouteImport } from './routes/_authenticated/my-plan'
import { Route as AuthenticatedMyDashboardRouteImport } from './routes/_authenticated/my-dashboard'
import { Route as AuthenticatedMeuPlanoRouteImport } from './routes/_authenticated/meu-plano'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFeedbacksRouteImport } from './routes/_authenticated/feedbacks'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProtocolosIndexRouteImport } from './routes/_authenticated/protocolos.index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedAnamnesesIndexRouteImport } from './routes/_authenticated/anamneses.index'
import { Route as CSlugCodeRouteImport } from './routes/c.$slug.$code'
import { Route as AuthenticatedProtocolosProtocolIdRouteImport } from './routes/_authenticated/protocolos.$protocolId'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients/new'
import { Route as AuthenticatedOnboardingPatientRouteImport } from './routes/_authenticated/onboarding/patient'
import { Route as AuthenticatedOnboardingNutritionistRouteImport } from './routes/_authenticated/onboarding/nutritionist'
import { Route as AuthenticatedMyPlanUpdateHealthProfileRouteImport } from './routes/_authenticated/my-plan.update-health-profile'
import { Route as AuthenticatedMyPlanSettingsRouteImport } from './routes/_authenticated/my-plan.settings'
import { Route as AuthenticatedMyPlanProtocolosRouteImport } from './routes/_authenticated/my-plan.protocolos'
import { Route as AuthenticatedMyPlanPhysicalAssessmentRouteImport } from './routes/_authenticated/my-plan.physical-assessment'
import { Route as AuthenticatedMyPlanFeedbackRouteImport } from './routes/_authenticated/my-plan.feedback'
import { Route as AuthenticatedMyPlanAnamneseRouteImport } from './routes/_authenticated/my-plan.anamnese'
import { Route as AuthenticatedMeuPlanoUpdateHealthProfileRouteImport } from './routes/_authenticated/meu-plano.update-health-profile'
import { Route as AuthenticatedMeuPlanoSettingsRouteImport } from './routes/_authenticated/meu-plano.settings'
import { Route as AuthenticatedMeuPlanoProtocolosRouteImport } from './routes/_authenticated/meu-plano.protocolos'
import { Route as AuthenticatedMeuPlanoPhysicalAssessmentRouteImport } from './routes/_authenticated/meu-plano.physical-assessment'
import { Route as AuthenticatedMeuPlanoFeedbackRouteImport } from './routes/_authenticated/meu-plano.feedback'
import { Route as AuthenticatedMeuPlanoAnamneseRouteImport } from './routes/_authenticated/meu-plano.anamnese'
import { Route as AuthenticatedAnamnesesIdRouteImport } from './routes/_authenticated/anamneses.$id'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminProfissionaisRouteImport } from './routes/_authenticated/admin.profissionais'
import { Route as AuthenticatedAdminPacientesRouteImport } from './routes/_authenticated/admin.pacientes'
import { Route as AuthenticatedAdminLogosRouteImport } from './routes/_authenticated/admin.logos'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminLandingRouteImport } from './routes/_authenticated/admin.landing'
import { Route as AuthenticatedPatientsIdIndexRouteImport } from './routes/_authenticated/patients/$id/index'
import { Route as AuthenticatedProtocolosProtocolIdEditarRouteImport } from './routes/_authenticated/protocolos.$protocolId.editar'
import { Route as AuthenticatedPatientsIdFeedbacksRouteImport } from './routes/_authenticated/patients/$id/feedbacks'
import { Route as AuthenticatedPatientsIdDietRouteImport } from './routes/_authenticated/patients/$id/diet'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoTestRoute = LogoTestRouteImport.update({
  id: '/logo-test',
  path: '/logo-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPatientRoute = SignupPatientRouteImport.update({
  id: '/signup/patient',
  path: '/signup/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupNutritionistRoute = SignupNutritionistRouteImport.update({
  id: '/signup/nutritionist',
  path: '/signup/nutritionist',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/auth/check-email',
  path: '/auth/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesV2EditorRoute =
  AuthenticatedTemplatesV2EditorRouteImport.update({
    id: '/templates-v2-editor',
    path: '/templates-v2-editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtocolosRoute = AuthenticatedProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyPlanV2PreviewRoute =
  AuthenticatedMyPlanV2PreviewRouteImport.update({
    id: '/my-plan-v2-preview',
    path: '/my-plan-v2-preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyPlanRoute = AuthenticatedMyPlanRouteImport.update({
  id: '/my-plan',
  path: '/my-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyDashboardRoute =
  AuthenticatedMyDashboardRouteImport.update({
    id: '/my-dashboard',
    path: '/my-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeuPlanoRoute = AuthenticatedMeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbacksRoute = AuthenticatedFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtocolosIndexRoute =
  AuthenticatedProtocolosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProtocolosRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnamnesesIndexRoute =
  AuthenticatedAnamnesesIndexRouteImport.update({
    id: '/anamneses/',
    path: '/anamneses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CSlugCodeRoute = CSlugCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CSlugRoute,
} as any)
const AuthenticatedProtocolosProtocolIdRoute =
  AuthenticatedProtocolosProtocolIdRouteImport.update({
    id: '/$protocolId',
    path: '/$protocolId',
    getParentRoute: () => AuthenticatedProtocolosRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/patients/new',
    path: '/patients/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingPatientRoute =
  AuthenticatedOnboardingPatientRouteImport.update({
    id: '/onboarding/patient',
    path: '/onboarding/patient',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingNutritionistRoute =
  AuthenticatedOnboardingNutritionistRouteImport.update({
    id: '/onboarding/nutritionist',
    path: '/onboarding/nutritionist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyPlanUpdateHealthProfileRoute =
  AuthenticatedMyPlanUpdateHealthProfileRouteImport.update({
    id: '/update-health-profile',
    path: '/update-health-profile',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMyPlanSettingsRoute =
  AuthenticatedMyPlanSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMyPlanProtocolosRoute =
  AuthenticatedMyPlanProtocolosRouteImport.update({
    id: '/protocolos',
    path: '/protocolos',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMyPlanPhysicalAssessmentRoute =
  AuthenticatedMyPlanPhysicalAssessmentRouteImport.update({
    id: '/physical-assessment',
    path: '/physical-assessment',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMyPlanFeedbackRoute =
  AuthenticatedMyPlanFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMyPlanAnamneseRoute =
  AuthenticatedMyPlanAnamneseRouteImport.update({
    id: '/anamnese',
    path: '/anamnese',
    getParentRoute: () => AuthenticatedMyPlanRoute,
  } as any)
const AuthenticatedMeuPlanoUpdateHealthProfileRoute =
  AuthenticatedMeuPlanoUpdateHealthProfileRouteImport.update({
    id: '/update-health-profile',
    path: '/update-health-profile',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedMeuPlanoSettingsRoute =
  AuthenticatedMeuPlanoSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedMeuPlanoProtocolosRoute =
  AuthenticatedMeuPlanoProtocolosRouteImport.update({
    id: '/protocolos',
    path: '/protocolos',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedMeuPlanoPhysicalAssessmentRoute =
  AuthenticatedMeuPlanoPhysicalAssessmentRouteImport.update({
    id: '/physical-assessment',
    path: '/physical-assessment',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedMeuPlanoFeedbackRoute =
  AuthenticatedMeuPlanoFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedMeuPlanoAnamneseRoute =
  AuthenticatedMeuPlanoAnamneseRouteImport.update({
    id: '/anamnese',
    path: '/anamnese',
    getParentRoute: () => AuthenticatedMeuPlanoRoute,
  } as any)
const AuthenticatedAnamnesesIdRoute =
  AuthenticatedAnamnesesIdRouteImport.update({
    id: '/anamneses/$id',
    path: '/anamneses/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfissionaisRoute =
  AuthenticatedAdminProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPacientesRoute =
  AuthenticatedAdminPacientesRouteImport.update({
    id: '/pacientes',
    path: '/pacientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogosRoute = AuthenticatedAdminLogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLandingRoute =
  AuthenticatedAdminLandingRouteImport.update({
    id: '/landing',
    path: '/landing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPatientsIdIndexRoute =
  AuthenticatedPatientsIdIndexRouteImport.update({
    id: '/patients/$id/',
    path: '/patients/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProtocolosProtocolIdEditarRoute =
  AuthenticatedProtocolosProtocolIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedProtocolosProtocolIdRoute,
  } as any)
const AuthenticatedPatientsIdFeedbacksRoute =
  AuthenticatedPatientsIdFeedbacksRouteImport.update({
    id: '/patients/$id/feedbacks',
    path: '/patients/$id/feedbacks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIdDietRoute =
  AuthenticatedPatientsIdDietRouteImport.update({
    id: '/patients/$id/diet',
    path: '/patients/$id/diet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logo-test': typeof LogoTestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/meu-plano': typeof AuthenticatedMeuPlanoRouteWithChildren
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/my-plan': typeof AuthenticatedMyPlanRouteWithChildren
  '/my-plan-v2-preview': typeof AuthenticatedMyPlanV2PreviewRoute
  '/protocolos': typeof AuthenticatedProtocolosRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/templates-v2-editor': typeof AuthenticatedTemplatesV2EditorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/n/$slug': typeof NSlugRoute
  '/signup/nutritionist': typeof SignupNutritionistRoute
  '/signup/patient': typeof SignupPatientRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/admin/pacientes': typeof AuthenticatedAdminPacientesRoute
  '/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/anamneses/$id': typeof AuthenticatedAnamnesesIdRoute
  '/meu-plano/anamnese': typeof AuthenticatedMeuPlanoAnamneseRoute
  '/meu-plano/feedback': typeof AuthenticatedMeuPlanoFeedbackRoute
  '/meu-plano/physical-assessment': typeof AuthenticatedMeuPlanoPhysicalAssessmentRoute
  '/meu-plano/protocolos': typeof AuthenticatedMeuPlanoProtocolosRoute
  '/meu-plano/settings': typeof AuthenticatedMeuPlanoSettingsRoute
  '/meu-plano/update-health-profile': typeof AuthenticatedMeuPlanoUpdateHealthProfileRoute
  '/my-plan/anamnese': typeof AuthenticatedMyPlanAnamneseRoute
  '/my-plan/feedback': typeof AuthenticatedMyPlanFeedbackRoute
  '/my-plan/physical-assessment': typeof AuthenticatedMyPlanPhysicalAssessmentRoute
  '/my-plan/protocolos': typeof AuthenticatedMyPlanProtocolosRoute
  '/my-plan/settings': typeof AuthenticatedMyPlanSettingsRoute
  '/my-plan/update-health-profile': typeof AuthenticatedMyPlanUpdateHealthProfileRoute
  '/onboarding/nutritionist': typeof AuthenticatedOnboardingNutritionistRoute
  '/onboarding/patient': typeof AuthenticatedOnboardingPatientRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/protocolos/$protocolId': typeof AuthenticatedProtocolosProtocolIdRouteWithChildren
  '/c/$slug/$code': typeof CSlugCodeRoute
  '/anamneses/': typeof AuthenticatedAnamnesesIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/protocolos/': typeof AuthenticatedProtocolosIndexRoute
  '/patients/$id/diet': typeof AuthenticatedPatientsIdDietRoute
  '/patients/$id/feedbacks': typeof AuthenticatedPatientsIdFeedbacksRoute
  '/protocolos/$protocolId/editar': typeof AuthenticatedProtocolosProtocolIdEditarRoute
  '/patients/$id/': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logo-test': typeof LogoTestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/meu-plano': typeof AuthenticatedMeuPlanoRouteWithChildren
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/my-plan': typeof AuthenticatedMyPlanRouteWithChildren
  '/my-plan-v2-preview': typeof AuthenticatedMyPlanV2PreviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/templates-v2-editor': typeof AuthenticatedTemplatesV2EditorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/n/$slug': typeof NSlugRoute
  '/signup/nutritionist': typeof SignupNutritionistRoute
  '/signup/patient': typeof SignupPatientRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/admin/pacientes': typeof AuthenticatedAdminPacientesRoute
  '/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/anamneses/$id': typeof AuthenticatedAnamnesesIdRoute
  '/meu-plano/anamnese': typeof AuthenticatedMeuPlanoAnamneseRoute
  '/meu-plano/feedback': typeof AuthenticatedMeuPlanoFeedbackRoute
  '/meu-plano/physical-assessment': typeof AuthenticatedMeuPlanoPhysicalAssessmentRoute
  '/meu-plano/protocolos': typeof AuthenticatedMeuPlanoProtocolosRoute
  '/meu-plano/settings': typeof AuthenticatedMeuPlanoSettingsRoute
  '/meu-plano/update-health-profile': typeof AuthenticatedMeuPlanoUpdateHealthProfileRoute
  '/my-plan/anamnese': typeof AuthenticatedMyPlanAnamneseRoute
  '/my-plan/feedback': typeof AuthenticatedMyPlanFeedbackRoute
  '/my-plan/physical-assessment': typeof AuthenticatedMyPlanPhysicalAssessmentRoute
  '/my-plan/protocolos': typeof AuthenticatedMyPlanProtocolosRoute
  '/my-plan/settings': typeof AuthenticatedMyPlanSettingsRoute
  '/my-plan/update-health-profile': typeof AuthenticatedMyPlanUpdateHealthProfileRoute
  '/onboarding/nutritionist': typeof AuthenticatedOnboardingNutritionistRoute
  '/onboarding/patient': typeof AuthenticatedOnboardingPatientRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/protocolos/$protocolId': typeof AuthenticatedProtocolosProtocolIdRouteWithChildren
  '/c/$slug/$code': typeof CSlugCodeRoute
  '/anamneses': typeof AuthenticatedAnamnesesIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/protocolos': typeof AuthenticatedProtocolosIndexRoute
  '/patients/$id/diet': typeof AuthenticatedPatientsIdDietRoute
  '/patients/$id/feedbacks': typeof AuthenticatedPatientsIdFeedbacksRoute
  '/protocolos/$protocolId/editar': typeof AuthenticatedProtocolosProtocolIdEditarRoute
  '/patients/$id': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logo-test': typeof LogoTestRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/feedbacks': typeof AuthenticatedFeedbacksRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/meu-plano': typeof AuthenticatedMeuPlanoRouteWithChildren
  '/_authenticated/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/_authenticated/my-plan': typeof AuthenticatedMyPlanRouteWithChildren
  '/_authenticated/my-plan-v2-preview': typeof AuthenticatedMyPlanV2PreviewRoute
  '/_authenticated/protocolos': typeof AuthenticatedProtocolosRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/templates-v2-editor': typeof AuthenticatedTemplatesV2EditorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/n/$slug': typeof NSlugRoute
  '/signup/nutritionist': typeof SignupNutritionistRoute
  '/signup/patient': typeof SignupPatientRoute
  '/_authenticated/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/logos': typeof AuthenticatedAdminLogosRoute
  '/_authenticated/admin/pacientes': typeof AuthenticatedAdminPacientesRoute
  '/_authenticated/admin/profissionais': typeof AuthenticatedAdminProfissionaisRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/anamneses/$id': typeof AuthenticatedAnamnesesIdRoute
  '/_authenticated/meu-plano/anamnese': typeof AuthenticatedMeuPlanoAnamneseRoute
  '/_authenticated/meu-plano/feedback': typeof AuthenticatedMeuPlanoFeedbackRoute
  '/_authenticated/meu-plano/physical-assessment': typeof AuthenticatedMeuPlanoPhysicalAssessmentRoute
  '/_authenticated/meu-plano/protocolos': typeof AuthenticatedMeuPlanoProtocolosRoute
  '/_authenticated/meu-plano/settings': typeof AuthenticatedMeuPlanoSettingsRoute
  '/_authenticated/meu-plano/update-health-profile': typeof AuthenticatedMeuPlanoUpdateHealthProfileRoute
  '/_authenticated/my-plan/anamnese': typeof AuthenticatedMyPlanAnamneseRoute
  '/_authenticated/my-plan/feedback': typeof AuthenticatedMyPlanFeedbackRoute
  '/_authenticated/my-plan/physical-assessment': typeof AuthenticatedMyPlanPhysicalAssessmentRoute
  '/_authenticated/my-plan/protocolos': typeof AuthenticatedMyPlanProtocolosRoute
  '/_authenticated/my-plan/settings': typeof AuthenticatedMyPlanSettingsRoute
  '/_authenticated/my-plan/update-health-profile': typeof AuthenticatedMyPlanUpdateHealthProfileRoute
  '/_authenticated/onboarding/nutritionist': typeof AuthenticatedOnboardingNutritionistRoute
  '/_authenticated/onboarding/patient': typeof AuthenticatedOnboardingPatientRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/protocolos/$protocolId': typeof AuthenticatedProtocolosProtocolIdRouteWithChildren
  '/c/$slug/$code': typeof CSlugCodeRoute
  '/_authenticated/anamneses/': typeof AuthenticatedAnamnesesIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/protocolos/': typeof AuthenticatedProtocolosIndexRoute
  '/_authenticated/patients/$id/diet': typeof AuthenticatedPatientsIdDietRoute
  '/_authenticated/patients/$id/feedbacks': typeof AuthenticatedPatientsIdFeedbacksRoute
  '/_authenticated/protocolos/$protocolId/editar': typeof AuthenticatedProtocolosProtocolIdEditarRoute
  '/_authenticated/patients/$id/': typeof AuthenticatedPatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/logo-test'
    | '/privacidade'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/dashboard'
    | '/feedbacks'
    | '/financeiro'
    | '/insights'
    | '/meu-plano'
    | '/my-dashboard'
    | '/my-plan'
    | '/my-plan-v2-preview'
    | '/protocolos'
    | '/settings'
    | '/templates'
    | '/templates-v2-editor'
    | '/auth/check-email'
    | '/c/$slug'
    | '/n/$slug'
    | '/signup/nutritionist'
    | '/signup/patient'
    | '/admin/landing'
    | '/admin/leads'
    | '/admin/logos'
    | '/admin/pacientes'
    | '/admin/profissionais'
    | '/admin/settings'
    | '/anamneses/$id'
    | '/meu-plano/anamnese'
    | '/meu-plano/feedback'
    | '/meu-plano/physical-assessment'
    | '/meu-plano/protocolos'
    | '/meu-plano/settings'
    | '/meu-plano/update-health-profile'
    | '/my-plan/anamnese'
    | '/my-plan/feedback'
    | '/my-plan/physical-assessment'
    | '/my-plan/protocolos'
    | '/my-plan/settings'
    | '/my-plan/update-health-profile'
    | '/onboarding/nutritionist'
    | '/onboarding/patient'
    | '/patients/new'
    | '/protocolos/$protocolId'
    | '/c/$slug/$code'
    | '/anamneses/'
    | '/patients/'
    | '/protocolos/'
    | '/patients/$id/diet'
    | '/patients/$id/feedbacks'
    | '/protocolos/$protocolId/editar'
    | '/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/logo-test'
    | '/privacidade'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/admin'
    | '/dashboard'
    | '/feedbacks'
    | '/financeiro'
    | '/insights'
    | '/meu-plano'
    | '/my-dashboard'
    | '/my-plan'
    | '/my-plan-v2-preview'
    | '/settings'
    | '/templates'
    | '/templates-v2-editor'
    | '/auth/check-email'
    | '/c/$slug'
    | '/n/$slug'
    | '/signup/nutritionist'
    | '/signup/patient'
    | '/admin/landing'
    | '/admin/leads'
    | '/admin/logos'
    | '/admin/pacientes'
    | '/admin/profissionais'
    | '/admin/settings'
    | '/anamneses/$id'
    | '/meu-plano/anamnese'
    | '/meu-plano/feedback'
    | '/meu-plano/physical-assessment'
    | '/meu-plano/protocolos'
    | '/meu-plano/settings'
    | '/meu-plano/update-health-profile'
    | '/my-plan/anamnese'
    | '/my-plan/feedback'
    | '/my-plan/physical-assessment'
    | '/my-plan/protocolos'
    | '/my-plan/settings'
    | '/my-plan/update-health-profile'
    | '/onboarding/nutritionist'
    | '/onboarding/patient'
    | '/patients/new'
    | '/protocolos/$protocolId'
    | '/c/$slug/$code'
    | '/anamneses'
    | '/patients'
    | '/protocolos'
    | '/patients/$id/diet'
    | '/patients/$id/feedbacks'
    | '/protocolos/$protocolId/editar'
    | '/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/forgot-password'
    | '/logo-test'
    | '/privacidade'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/feedbacks'
    | '/_authenticated/financeiro'
    | '/_authenticated/insights'
    | '/_authenticated/meu-plano'
    | '/_authenticated/my-dashboard'
    | '/_authenticated/my-plan'
    | '/_authenticated/my-plan-v2-preview'
    | '/_authenticated/protocolos'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/templates-v2-editor'
    | '/auth/check-email'
    | '/c/$slug'
    | '/n/$slug'
    | '/signup/nutritionist'
    | '/signup/patient'
    | '/_authenticated/admin/landing'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/logos'
    | '/_authenticated/admin/pacientes'
    | '/_authenticated/admin/profissionais'
    | '/_authenticated/admin/settings'
    | '/_authenticated/anamneses/$id'
    | '/_authenticated/meu-plano/anamnese'
    | '/_authenticated/meu-plano/feedback'
    | '/_authenticated/meu-plano/physical-assessment'
    | '/_authenticated/meu-plano/protocolos'
    | '/_authenticated/meu-plano/settings'
    | '/_authenticated/meu-plano/update-health-profile'
    | '/_authenticated/my-plan/anamnese'
    | '/_authenticated/my-plan/feedback'
    | '/_authenticated/my-plan/physical-assessment'
    | '/_authenticated/my-plan/protocolos'
    | '/_authenticated/my-plan/settings'
    | '/_authenticated/my-plan/update-health-profile'
    | '/_authenticated/onboarding/nutritionist'
    | '/_authenticated/onboarding/patient'
    | '/_authenticated/patients/new'
    | '/_authenticated/protocolos/$protocolId'
    | '/c/$slug/$code'
    | '/_authenticated/anamneses/'
    | '/_authenticated/patients/'
    | '/_authenticated/protocolos/'
    | '/_authenticated/patients/$id/diet'
    | '/_authenticated/patients/$id/feedbacks'
    | '/_authenticated/protocolos/$protocolId/editar'
    | '/_authenticated/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LogoTestRoute: typeof LogoTestRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  CSlugRoute: typeof CSlugRouteWithChildren
  NSlugRoute: typeof NSlugRoute
  SignupNutritionistRoute: typeof SignupNutritionistRoute
  SignupPatientRoute: typeof SignupPatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-test': {
      id: '/logo-test'
      path: '/logo-test'
      fullPath: '/logo-test'
      preLoaderRoute: typeof LogoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/patient': {
      id: '/signup/patient'
      path: '/signup/patient'
      fullPath: '/signup/patient'
      preLoaderRoute: typeof SignupPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/nutritionist': {
      id: '/signup/nutritionist'
      path: '/signup/nutritionist'
      fullPath: '/signup/nutritionist'
      preLoaderRoute: typeof SignupNutritionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/auth/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates-v2-editor': {
      id: '/_authenticated/templates-v2-editor'
      path: '/templates-v2-editor'
      fullPath: '/templates-v2-editor'
      preLoaderRoute: typeof AuthenticatedTemplatesV2EditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolos': {
      id: '/_authenticated/protocolos'
      path: '/protocolos'
      fullPath: '/protocolos'
      preLoaderRoute: typeof AuthenticatedProtocolosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-plan-v2-preview': {
      id: '/_authenticated/my-plan-v2-preview'
      path: '/my-plan-v2-preview'
      fullPath: '/my-plan-v2-preview'
      preLoaderRoute: typeof AuthenticatedMyPlanV2PreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-plan': {
      id: '/_authenticated/my-plan'
      path: '/my-plan'
      fullPath: '/my-plan'
      preLoaderRoute: typeof AuthenticatedMyPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-dashboard': {
      id: '/_authenticated/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof AuthenticatedMyDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-plano': {
      id: '/_authenticated/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof AuthenticatedMeuPlanoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedbacks': {
      id: '/_authenticated/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof AuthenticatedFeedbacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolos/': {
      id: '/_authenticated/protocolos/'
      path: '/'
      fullPath: '/protocolos/'
      preLoaderRoute: typeof AuthenticatedProtocolosIndexRouteImport
      parentRoute: typeof AuthenticatedProtocolosRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anamneses/': {
      id: '/_authenticated/anamneses/'
      path: '/anamneses'
      fullPath: '/anamneses/'
      preLoaderRoute: typeof AuthenticatedAnamnesesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/c/$slug/$code': {
      id: '/c/$slug/$code'
      path: '/$code'
      fullPath: '/c/$slug/$code'
      preLoaderRoute: typeof CSlugCodeRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/_authenticated/protocolos/$protocolId': {
      id: '/_authenticated/protocolos/$protocolId'
      path: '/$protocolId'
      fullPath: '/protocolos/$protocolId'
      preLoaderRoute: typeof AuthenticatedProtocolosProtocolIdRouteImport
      parentRoute: typeof AuthenticatedProtocolosRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/patient': {
      id: '/_authenticated/onboarding/patient'
      path: '/onboarding/patient'
      fullPath: '/onboarding/patient'
      preLoaderRoute: typeof AuthenticatedOnboardingPatientRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/nutritionist': {
      id: '/_authenticated/onboarding/nutritionist'
      path: '/onboarding/nutritionist'
      fullPath: '/onboarding/nutritionist'
      preLoaderRoute: typeof AuthenticatedOnboardingNutritionistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-plan/update-health-profile': {
      id: '/_authenticated/my-plan/update-health-profile'
      path: '/update-health-profile'
      fullPath: '/my-plan/update-health-profile'
      preLoaderRoute: typeof AuthenticatedMyPlanUpdateHealthProfileRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/my-plan/settings': {
      id: '/_authenticated/my-plan/settings'
      path: '/settings'
      fullPath: '/my-plan/settings'
      preLoaderRoute: typeof AuthenticatedMyPlanSettingsRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/my-plan/protocolos': {
      id: '/_authenticated/my-plan/protocolos'
      path: '/protocolos'
      fullPath: '/my-plan/protocolos'
      preLoaderRoute: typeof AuthenticatedMyPlanProtocolosRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/my-plan/physical-assessment': {
      id: '/_authenticated/my-plan/physical-assessment'
      path: '/physical-assessment'
      fullPath: '/my-plan/physical-assessment'
      preLoaderRoute: typeof AuthenticatedMyPlanPhysicalAssessmentRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/my-plan/feedback': {
      id: '/_authenticated/my-plan/feedback'
      path: '/feedback'
      fullPath: '/my-plan/feedback'
      preLoaderRoute: typeof AuthenticatedMyPlanFeedbackRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/my-plan/anamnese': {
      id: '/_authenticated/my-plan/anamnese'
      path: '/anamnese'
      fullPath: '/my-plan/anamnese'
      preLoaderRoute: typeof AuthenticatedMyPlanAnamneseRouteImport
      parentRoute: typeof AuthenticatedMyPlanRoute
    }
    '/_authenticated/meu-plano/update-health-profile': {
      id: '/_authenticated/meu-plano/update-health-profile'
      path: '/update-health-profile'
      fullPath: '/meu-plano/update-health-profile'
      preLoaderRoute: typeof AuthenticatedMeuPlanoUpdateHealthProfileRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/meu-plano/settings': {
      id: '/_authenticated/meu-plano/settings'
      path: '/settings'
      fullPath: '/meu-plano/settings'
      preLoaderRoute: typeof AuthenticatedMeuPlanoSettingsRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/meu-plano/protocolos': {
      id: '/_authenticated/meu-plano/protocolos'
      path: '/protocolos'
      fullPath: '/meu-plano/protocolos'
      preLoaderRoute: typeof AuthenticatedMeuPlanoProtocolosRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/meu-plano/physical-assessment': {
      id: '/_authenticated/meu-plano/physical-assessment'
      path: '/physical-assessment'
      fullPath: '/meu-plano/physical-assessment'
      preLoaderRoute: typeof AuthenticatedMeuPlanoPhysicalAssessmentRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/meu-plano/feedback': {
      id: '/_authenticated/meu-plano/feedback'
      path: '/feedback'
      fullPath: '/meu-plano/feedback'
      preLoaderRoute: typeof AuthenticatedMeuPlanoFeedbackRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/meu-plano/anamnese': {
      id: '/_authenticated/meu-plano/anamnese'
      path: '/anamnese'
      fullPath: '/meu-plano/anamnese'
      preLoaderRoute: typeof AuthenticatedMeuPlanoAnamneseRouteImport
      parentRoute: typeof AuthenticatedMeuPlanoRoute
    }
    '/_authenticated/anamneses/$id': {
      id: '/_authenticated/anamneses/$id'
      path: '/anamneses/$id'
      fullPath: '/anamneses/$id'
      preLoaderRoute: typeof AuthenticatedAnamnesesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profissionais': {
      id: '/_authenticated/admin/profissionais'
      path: '/profissionais'
      fullPath: '/admin/profissionais'
      preLoaderRoute: typeof AuthenticatedAdminProfissionaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pacientes': {
      id: '/_authenticated/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AuthenticatedAdminPacientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logos': {
      id: '/_authenticated/admin/logos'
      path: '/logos'
      fullPath: '/admin/logos'
      preLoaderRoute: typeof AuthenticatedAdminLogosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/landing': {
      id: '/_authenticated/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AuthenticatedAdminLandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/patients/$id/': {
      id: '/_authenticated/patients/$id/'
      path: '/patients/$id'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof AuthenticatedPatientsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocolos/$protocolId/editar': {
      id: '/_authenticated/protocolos/$protocolId/editar'
      path: '/editar'
      fullPath: '/protocolos/$protocolId/editar'
      preLoaderRoute: typeof AuthenticatedProtocolosProtocolIdEditarRouteImport
      parentRoute: typeof AuthenticatedProtocolosProtocolIdRoute
    }
    '/_authenticated/patients/$id/feedbacks': {
      id: '/_authenticated/patients/$id/feedbacks'
      path: '/patients/$id/feedbacks'
      fullPath: '/patients/$id/feedbacks'
      preLoaderRoute: typeof AuthenticatedPatientsIdFeedbacksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$id/diet': {
      id: '/_authenticated/patients/$id/diet'
      path: '/patients/$id/diet'
      fullPath: '/patients/$id/diet'
      preLoaderRoute: typeof AuthenticatedPatientsIdDietRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLandingRoute: typeof AuthenticatedAdminLandingRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLogosRoute: typeof AuthenticatedAdminLogosRoute
  AuthenticatedAdminPacientesRoute: typeof AuthenticatedAdminPacientesRoute
  AuthenticatedAdminProfissionaisRoute: typeof AuthenticatedAdminProfissionaisRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLandingRoute: AuthenticatedAdminLandingRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLogosRoute: AuthenticatedAdminLogosRoute,
  AuthenticatedAdminPacientesRoute: AuthenticatedAdminPacientesRoute,
  AuthenticatedAdminProfissionaisRoute: AuthenticatedAdminProfissionaisRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMeuPlanoRouteChildren {
  AuthenticatedMeuPlanoAnamneseRoute: typeof AuthenticatedMeuPlanoAnamneseRoute
  AuthenticatedMeuPlanoFeedbackRoute: typeof AuthenticatedMeuPlanoFeedbackRoute
  AuthenticatedMeuPlanoPhysicalAssessmentRoute: typeof AuthenticatedMeuPlanoPhysicalAssessmentRoute
  AuthenticatedMeuPlanoProtocolosRoute: typeof AuthenticatedMeuPlanoProtocolosRoute
  AuthenticatedMeuPlanoSettingsRoute: typeof AuthenticatedMeuPlanoSettingsRoute
  AuthenticatedMeuPlanoUpdateHealthProfileRoute: typeof AuthenticatedMeuPlanoUpdateHealthProfileRoute
}

const AuthenticatedMeuPlanoRouteChildren: AuthenticatedMeuPlanoRouteChildren = {
  AuthenticatedMeuPlanoAnamneseRoute: AuthenticatedMeuPlanoAnamneseRoute,
  AuthenticatedMeuPlanoFeedbackRoute: AuthenticatedMeuPlanoFeedbackRoute,
  AuthenticatedMeuPlanoPhysicalAssessmentRoute:
    AuthenticatedMeuPlanoPhysicalAssessmentRoute,
  AuthenticatedMeuPlanoProtocolosRoute: AuthenticatedMeuPlanoProtocolosRoute,
  AuthenticatedMeuPlanoSettingsRoute: AuthenticatedMeuPlanoSettingsRoute,
  AuthenticatedMeuPlanoUpdateHealthProfileRoute:
    AuthenticatedMeuPlanoUpdateHealthProfileRoute,
}

const AuthenticatedMeuPlanoRouteWithChildren =
  AuthenticatedMeuPlanoRoute._addFileChildren(
    AuthenticatedMeuPlanoRouteChildren,
  )

interface AuthenticatedMyPlanRouteChildren {
  AuthenticatedMyPlanAnamneseRoute: typeof AuthenticatedMyPlanAnamneseRoute
  AuthenticatedMyPlanFeedbackRoute: typeof AuthenticatedMyPlanFeedbackRoute
  AuthenticatedMyPlanPhysicalAssessmentRoute: typeof AuthenticatedMyPlanPhysicalAssessmentRoute
  AuthenticatedMyPlanProtocolosRoute: typeof AuthenticatedMyPlanProtocolosRoute
  AuthenticatedMyPlanSettingsRoute: typeof AuthenticatedMyPlanSettingsRoute
  AuthenticatedMyPlanUpdateHealthProfileRoute: typeof AuthenticatedMyPlanUpdateHealthProfileRoute
}

const AuthenticatedMyPlanRouteChildren: AuthenticatedMyPlanRouteChildren = {
  AuthenticatedMyPlanAnamneseRoute: AuthenticatedMyPlanAnamneseRoute,
  AuthenticatedMyPlanFeedbackRoute: AuthenticatedMyPlanFeedbackRoute,
  AuthenticatedMyPlanPhysicalAssessmentRoute:
    AuthenticatedMyPlanPhysicalAssessmentRoute,
  AuthenticatedMyPlanProtocolosRoute: AuthenticatedMyPlanProtocolosRoute,
  AuthenticatedMyPlanSettingsRoute: AuthenticatedMyPlanSettingsRoute,
  AuthenticatedMyPlanUpdateHealthProfileRoute:
    AuthenticatedMyPlanUpdateHealthProfileRoute,
}

const AuthenticatedMyPlanRouteWithChildren =
  AuthenticatedMyPlanRoute._addFileChildren(AuthenticatedMyPlanRouteChildren)

interface AuthenticatedProtocolosProtocolIdRouteChildren {
  AuthenticatedProtocolosProtocolIdEditarRoute: typeof AuthenticatedProtocolosProtocolIdEditarRoute
}

const AuthenticatedProtocolosProtocolIdRouteChildren: AuthenticatedProtocolosProtocolIdRouteChildren =
  {
    AuthenticatedProtocolosProtocolIdEditarRoute:
      AuthenticatedProtocolosProtocolIdEditarRoute,
  }

const AuthenticatedProtocolosProtocolIdRouteWithChildren =
  AuthenticatedProtocolosProtocolIdRoute._addFileChildren(
    AuthenticatedProtocolosProtocolIdRouteChildren,
  )

interface AuthenticatedProtocolosRouteChildren {
  AuthenticatedProtocolosProtocolIdRoute: typeof AuthenticatedProtocolosProtocolIdRouteWithChildren
  AuthenticatedProtocolosIndexRoute: typeof AuthenticatedProtocolosIndexRoute
}

const AuthenticatedProtocolosRouteChildren: AuthenticatedProtocolosRouteChildren =
  {
    AuthenticatedProtocolosProtocolIdRoute:
      AuthenticatedProtocolosProtocolIdRouteWithChildren,
    AuthenticatedProtocolosIndexRoute: AuthenticatedProtocolosIndexRoute,
  }

const AuthenticatedProtocolosRouteWithChildren =
  AuthenticatedProtocolosRoute._addFileChildren(
    AuthenticatedProtocolosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeedbacksRoute: typeof AuthenticatedFeedbacksRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMeuPlanoRoute: typeof AuthenticatedMeuPlanoRouteWithChildren
  AuthenticatedMyDashboardRoute: typeof AuthenticatedMyDashboardRoute
  AuthenticatedMyPlanRoute: typeof AuthenticatedMyPlanRouteWithChildren
  AuthenticatedMyPlanV2PreviewRoute: typeof AuthenticatedMyPlanV2PreviewRoute
  AuthenticatedProtocolosRoute: typeof AuthenticatedProtocolosRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTemplatesV2EditorRoute: typeof AuthenticatedTemplatesV2EditorRoute
  AuthenticatedAnamnesesIdRoute: typeof AuthenticatedAnamnesesIdRoute
  AuthenticatedOnboardingNutritionistRoute: typeof AuthenticatedOnboardingNutritionistRoute
  AuthenticatedOnboardingPatientRoute: typeof AuthenticatedOnboardingPatientRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedAnamnesesIndexRoute: typeof AuthenticatedAnamnesesIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPatientsIdDietRoute: typeof AuthenticatedPatientsIdDietRoute
  AuthenticatedPatientsIdFeedbacksRoute: typeof AuthenticatedPatientsIdFeedbacksRoute
  AuthenticatedPatientsIdIndexRoute: typeof AuthenticatedPatientsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeedbacksRoute: AuthenticatedFeedbacksRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMeuPlanoRoute: AuthenticatedMeuPlanoRouteWithChildren,
  AuthenticatedMyDashboardRoute: AuthenticatedMyDashboardRoute,
  AuthenticatedMyPlanRoute: AuthenticatedMyPlanRouteWithChildren,
  AuthenticatedMyPlanV2PreviewRoute: AuthenticatedMyPlanV2PreviewRoute,
  AuthenticatedProtocolosRoute: AuthenticatedProtocolosRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTemplatesV2EditorRoute: AuthenticatedTemplatesV2EditorRoute,
  AuthenticatedAnamnesesIdRoute: AuthenticatedAnamnesesIdRoute,
  AuthenticatedOnboardingNutritionistRoute:
    AuthenticatedOnboardingNutritionistRoute,
  AuthenticatedOnboardingPatientRoute: AuthenticatedOnboardingPatientRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedAnamnesesIndexRoute: AuthenticatedAnamnesesIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPatientsIdDietRoute: AuthenticatedPatientsIdDietRoute,
  AuthenticatedPatientsIdFeedbacksRoute: AuthenticatedPatientsIdFeedbacksRoute,
  AuthenticatedPatientsIdIndexRoute: AuthenticatedPatientsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CSlugRouteChildren {
  CSlugCodeRoute: typeof CSlugCodeRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugCodeRoute: CSlugCodeRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LogoTestRoute: LogoTestRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  CSlugRoute: CSlugRouteWithChildren,
  NSlugRoute: NSlugRoute,
  SignupNutritionistRoute: SignupNutritionistRoute,
  SignupPatientRoute: SignupPatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
